from typing import Dict, List  # Import type hints for better readability and tooling support.

# Store common disease records used by a basic rule-based diagnosis prototype.
COMMON_DISEASES: List[Dict[str, object]] = [
    {
        "disease": "Common Cold",  # Disease name.
        "symptoms": ["runny nose", "sore throat", "sneezing", "mild cough"],  # Typical symptoms.
        "possible_causes": ["rhinovirus", "seasonal exposure"],  # Common causes.
        "risk_factors": ["close contact", "weak immunity"],  # Factors increasing chance of illness.
        "recommended_tests": ["clinical exam"],  # Usual basic evaluation.
        "specialist": "General Physician",  # Suitable clinician.
        "urgent_red_flags": ["breathing difficulty", "high fever > 3 days"],  # Signs needing urgent review.
        "basic_care": ["rest", "fluids", "steam inhalation"],  # Home-level first care.
    },
    {
        "disease": "Influenza",  # Disease name.
        "symptoms": ["high fever", "body aches", "dry cough", "fatigue"],
        "possible_causes": ["influenza virus A/B"],
        "risk_factors": ["no vaccination", "crowded spaces"],
        "recommended_tests": ["rapid flu test", "PCR"],
        "specialist": "General Physician",
        "urgent_red_flags": ["chest pain", "confusion", "low oxygen"],
        "basic_care": ["rest", "hydration", "fever control"],
    },
    {
        "disease": "COVID-19",  # Disease name.
        "symptoms": ["fever", "dry cough", "loss of taste/smell", "breathlessness"],
        "possible_causes": ["SARS-CoV-2 infection"],
        "risk_factors": ["close contact", "chronic disease", "older age"],
        "recommended_tests": ["rapid antigen", "RT-PCR"],
        "specialist": "General Physician / Pulmonologist",
        "urgent_red_flags": ["oxygen saturation < 94%", "persistent chest pain"],
        "basic_care": ["isolation", "hydration", "medical monitoring"],
    },
    {
        "disease": "Acute Bronchitis",
        "symptoms": ["productive cough", "wheezing", "mild fever", "chest discomfort"],
        "possible_causes": ["viral respiratory infection", "airway irritation"],
        "risk_factors": ["smoking", "pollution exposure"],
        "recommended_tests": ["clinical exam", "chest X-ray if needed"],
        "specialist": "General Physician",
        "urgent_red_flags": ["shortness of breath", "blood in sputum"],
        "basic_care": ["rest", "warm fluids", "avoid smoke"],
    },
    {
        "disease": "Pneumonia",
        "symptoms": ["fever", "productive cough", "shortness of breath", "chest pain"],
        "possible_causes": ["bacterial infection", "viral infection"],
        "risk_factors": ["elderly age", "chronic lung disease"],
        "recommended_tests": ["chest X-ray", "CBC", "sputum culture"],
        "specialist": "Pulmonologist",
        "urgent_red_flags": ["low oxygen", "rapid breathing", "confusion"],
        "basic_care": ["prompt medical treatment", "hydration", "rest"],
    },
    {
        "disease": "Asthma",
        "symptoms": ["wheezing", "episodic breathlessness", "chest tightness", "night cough"],
        "possible_causes": ["airway inflammation", "allergic triggers"],
        "risk_factors": ["family history", "allergen exposure"],
        "recommended_tests": ["spirometry", "peak flow monitoring"],
        "specialist": "Pulmonologist",
        "urgent_red_flags": ["unable to speak full sentences", "blue lips"],
        "basic_care": ["inhaler adherence", "trigger avoidance"],
    },
    {
        "disease": "Allergic Rhinitis",
        "symptoms": ["sneezing", "itchy nose", "runny nose", "watery eyes"],
        "possible_causes": ["pollen", "dust mites", "pet dander"],
        "risk_factors": ["atopy", "family history of allergies"],
        "recommended_tests": ["allergy testing", "clinical exam"],
        "specialist": "ENT Specialist / Allergist",
        "urgent_red_flags": ["severe breathing difficulty"],
        "basic_care": ["allergen avoidance", "saline rinse"],
    },
    {
        "disease": "Sinusitis",
        "symptoms": ["facial pain", "nasal congestion", "thick nasal discharge", "headache"],
        "possible_causes": ["viral infection", "bacterial infection"],
        "risk_factors": ["allergies", "deviated septum"],
        "recommended_tests": ["clinical exam", "sinus CT in recurrent cases"],
        "specialist": "ENT Specialist",
        "urgent_red_flags": ["eye swelling", "high persistent fever"],
        "basic_care": ["steam inhalation", "hydration", "rest"],
    },
    {
        "disease": "Strep Throat",
        "symptoms": ["severe sore throat", "fever", "pain on swallowing", "swollen tonsils"],
        "possible_causes": ["group A streptococcus"],
        "risk_factors": ["school-age children", "close contact"],
        "recommended_tests": ["rapid strep test", "throat culture"],
        "specialist": "General Physician / ENT Specialist",
        "urgent_red_flags": ["drooling", "breathing difficulty"],
        "basic_care": ["warm fluids", "rest", "medical treatment"],
    },
    {
        "disease": "Otitis Media",
        "symptoms": ["ear pain", "fever", "reduced hearing", "irritability"],
        "possible_causes": ["middle ear infection"],
        "risk_factors": ["recent cold", "young age"],
        "recommended_tests": ["otoscopic exam"],
        "specialist": "ENT Specialist",
        "urgent_red_flags": ["ear discharge", "severe pain with swelling"],
        "basic_care": ["pain control", "follow physician advice"],
    },
    {
        "disease": "Conjunctivitis",
        "symptoms": ["red eye", "itching", "watery or sticky discharge", "gritty sensation"],
        "possible_causes": ["viral infection", "bacterial infection", "allergy"],
        "risk_factors": ["poor hand hygiene", "contact lens misuse"],
        "recommended_tests": ["eye examination"],
        "specialist": "Ophthalmologist",
        "urgent_red_flags": ["vision loss", "severe eye pain"],
        "basic_care": ["eye hygiene", "avoid sharing towels"],
    },
    {
        "disease": "Migraine",
        "symptoms": ["throbbing headache", "nausea", "light sensitivity", "sound sensitivity"],
        "possible_causes": ["neurological trigger patterns"],
        "risk_factors": ["stress", "sleep disturbance", "family history"],
        "recommended_tests": ["clinical diagnosis", "MRI if atypical"],
        "specialist": "Neurologist",
        "urgent_red_flags": ["sudden worst headache", "neurological deficit"],
        "basic_care": ["dark quiet room", "hydration", "trigger diary"],
    },
    {
        "disease": "Tension Headache",
        "symptoms": ["band-like head pressure", "neck tightness", "mild nausea", "fatigue"],
        "possible_causes": ["muscle tension", "stress"],
        "risk_factors": ["poor posture", "long screen time"],
        "recommended_tests": ["clinical evaluation"],
        "specialist": "General Physician",
        "urgent_red_flags": ["sudden severe headache", "fainting"],
        "basic_care": ["stress reduction", "hydration", "sleep hygiene"],
    },
    {
        "disease": "Gastroenteritis",
        "symptoms": ["diarrhea", "vomiting", "abdominal cramps", "fever"],
        "possible_causes": ["viral infection", "food contamination"],
        "risk_factors": ["unsafe food", "poor sanitation"],
        "recommended_tests": ["stool test if severe", "electrolyte check"],
        "specialist": "General Physician",
        "urgent_red_flags": ["dehydration", "blood in stool", "persistent vomiting"],
        "basic_care": ["oral rehydration", "light diet", "rest"],
    },
    {
        "disease": "GERD",
        "symptoms": ["heartburn", "acid regurgitation", "chest discomfort", "chronic cough"],
        "possible_causes": ["lower esophageal sphincter weakness"],
        "risk_factors": ["obesity", "late heavy meals"],
        "recommended_tests": ["clinical trial therapy", "endoscopy if persistent"],
        "specialist": "Gastroenterologist",
        "urgent_red_flags": ["difficulty swallowing", "black stools"],
        "basic_care": ["small meals", "avoid lying after food", "weight control"],
    },
    {
        "disease": "Peptic Ulcer Disease",
        "symptoms": ["burning upper abdominal pain", "bloating", "nausea", "early satiety"],
        "possible_causes": ["H. pylori", "NSAID overuse"],
        "risk_factors": ["smoking", "chronic NSAID use"],
        "recommended_tests": ["upper GI endoscopy", "H. pylori testing"],
        "specialist": "Gastroenterologist",
        "urgent_red_flags": ["vomiting blood", "black stools", "sudden severe pain"],
        "basic_care": ["avoid NSAID misuse", "timely treatment"],
    },
    {
        "disease": "Irritable Bowel Syndrome",
        "symptoms": ["abdominal pain", "bloating", "constipation", "diarrhea"],
        "possible_causes": ["gut-brain axis dysfunction"],
        "risk_factors": ["stress", "post-infectious bowel changes"],
        "recommended_tests": ["clinical criteria", "basic labs to exclude other causes"],
        "specialist": "Gastroenterologist",
        "urgent_red_flags": ["weight loss", "blood in stool", "night symptoms"],
        "basic_care": ["fiber adjustment", "stress management", "food trigger tracking"],
    },
    {
        "disease": "Constipation",
        "symptoms": ["hard stools", "infrequent bowel movements", "straining", "abdominal discomfort"],
        "possible_causes": ["low fiber diet", "dehydration", "low activity"],
        "risk_factors": ["sedentary lifestyle", "certain medications"],
        "recommended_tests": ["clinical assessment"],
        "specialist": "General Physician",
        "urgent_red_flags": ["severe pain", "blood in stool", "persistent vomiting"],
        "basic_care": ["increase fluids", "high-fiber diet", "regular exercise"],
    },
    {
        "disease": "Urinary Tract Infection",
        "symptoms": ["burning urination", "frequent urination", "lower abdominal pain", "cloudy urine"],
        "possible_causes": ["bacterial infection"],
        "risk_factors": ["female sex", "poor hydration", "urinary retention"],
        "recommended_tests": ["urine routine", "urine culture"],
        "specialist": "General Physician / Urologist",
        "urgent_red_flags": ["high fever", "flank pain", "vomiting"],
        "basic_care": ["hydration", "timely medical treatment"],
    },
    {
        "disease": "Kidney Stones",
        "symptoms": ["severe flank pain", "blood in urine", "nausea", "urinary urgency"],
        "possible_causes": ["mineral crystal formation"],
        "risk_factors": ["low water intake", "high salt diet"],
        "recommended_tests": ["urine analysis", "ultrasound", "CT KUB"],
        "specialist": "Urologist",
        "urgent_red_flags": ["fever with pain", "reduced urine output"],
        "basic_care": ["hydration", "pain control under supervision"],
    },
    {
        "disease": "Hypertension",
        "symptoms": ["often none", "headache", "dizziness", "blurred vision"],
        "possible_causes": ["primary hypertension", "renal/endocrine causes"],
        "risk_factors": ["high salt intake", "obesity", "family history"],
        "recommended_tests": ["repeated BP readings", "kidney function", "ECG"],
        "specialist": "General Physician / Cardiologist",
        "urgent_red_flags": ["BP crisis", "chest pain", "neurological symptoms"],
        "basic_care": ["salt reduction", "exercise", "regular monitoring"],
    },
    {
        "disease": "Coronary Artery Disease",
        "symptoms": ["chest pressure", "shortness of breath", "fatigue on exertion", "sweating"],
        "possible_causes": ["atherosclerosis"],
        "risk_factors": ["smoking", "diabetes", "high cholesterol"],
        "recommended_tests": ["ECG", "stress test", "echo", "angiography"],
        "specialist": "Cardiologist",
        "urgent_red_flags": ["persistent chest pain", "fainting", "cold sweats"],
        "basic_care": ["urgent medical assessment", "risk factor control"],
    },
    {
        "disease": "Heart Failure",
        "symptoms": ["breathlessness", "leg swelling", "fatigue", "orthopnea"],
        "possible_causes": ["ischemic heart disease", "long-standing hypertension"],
        "risk_factors": ["older age", "diabetes", "CAD"],
        "recommended_tests": ["echocardiography", "BNP", "chest X-ray"],
        "specialist": "Cardiologist",
        "urgent_red_flags": ["severe breathlessness", "pink frothy sputum"],
        "basic_care": ["salt/fluid guidance", "weight monitoring", "medication adherence"],
    },
    {
        "disease": "Type 2 Diabetes Mellitus",
        "symptoms": ["increased thirst", "frequent urination", "fatigue", "blurred vision"],
        "possible_causes": ["insulin resistance"],
        "risk_factors": ["obesity", "family history", "inactive lifestyle"],
        "recommended_tests": ["fasting glucose", "HbA1c", "OGTT"],
        "specialist": "Endocrinologist / General Physician",
        "urgent_red_flags": ["very high sugar", "confusion", "vomiting"],
        "basic_care": ["diet control", "exercise", "regular glucose checks"],
    },
    {
        "disease": "Hypothyroidism",
        "symptoms": ["fatigue", "weight gain", "cold intolerance", "dry skin"],
        "possible_causes": ["autoimmune thyroiditis", "iodine deficiency"],
        "risk_factors": ["female sex", "family history"],
        "recommended_tests": ["TSH", "free T4"],
        "specialist": "Endocrinologist",
        "urgent_red_flags": ["severe drowsiness", "slow heart rate"],
        "basic_care": ["regular thyroid medication", "follow-up labs"],
    },
    {
        "disease": "Hyperthyroidism",
        "symptoms": ["weight loss", "palpitations", "heat intolerance", "tremor"],
        "possible_causes": ["Graves disease", "toxic nodular goiter"],
        "risk_factors": ["autoimmune history", "female sex"],
        "recommended_tests": ["TSH", "free T4/T3", "thyroid scan"],
        "specialist": "Endocrinologist",
        "urgent_red_flags": ["severe tachycardia", "fever", "confusion"],
        "basic_care": ["medical management", "avoid excess iodine"],
    },
    {
        "disease": "Iron Deficiency Anemia",
        "symptoms": ["fatigue", "pallor", "shortness of breath", "dizziness"],
        "possible_causes": ["poor iron intake", "blood loss"],
        "risk_factors": ["heavy menstruation", "pregnancy", "poor diet"],
        "recommended_tests": ["CBC", "serum ferritin", "iron profile"],
        "specialist": "General Physician / Hematologist",
        "urgent_red_flags": ["chest pain", "fainting", "very low hemoglobin"],
        "basic_care": ["iron-rich diet", "doctor-prescribed supplements"],
    },
    {
        "disease": "Osteoarthritis",
        "symptoms": ["joint pain", "joint stiffness", "reduced mobility", "crepitus"],
        "possible_causes": ["cartilage wear and tear"],
        "risk_factors": ["ageing", "obesity", "joint overuse"],
        "recommended_tests": ["X-ray", "clinical exam"],
        "specialist": "Orthopedic Specialist",
        "urgent_red_flags": ["sudden hot swollen joint", "inability to bear weight"],
        "basic_care": ["weight management", "physiotherapy", "joint protection"],
    },
    {
        "disease": "Rheumatoid Arthritis",
        "symptoms": ["small joint swelling", "morning stiffness", "joint pain", "fatigue"],
        "possible_causes": ["autoimmune inflammation"],
        "risk_factors": ["female sex", "smoking", "family history"],
        "recommended_tests": ["RF", "anti-CCP", "ESR/CRP"],
        "specialist": "Rheumatologist",
        "urgent_red_flags": ["severe systemic weakness", "high fever with joint swelling"],
        "basic_care": ["early specialist care", "joint-friendly exercise"],
    },
    {
        "disease": "Gout",
        "symptoms": ["sudden severe joint pain", "red hot swollen joint", "night attacks", "limited movement"],
        "possible_causes": ["uric acid crystal deposition"],
        "risk_factors": ["high purine diet", "alcohol", "kidney disease"],
        "recommended_tests": ["serum uric acid", "joint fluid analysis"],
        "specialist": "Rheumatologist",
        "urgent_red_flags": ["fever with joint swelling", "multiple joint involvement"],
        "basic_care": ["hydration", "diet changes", "medical therapy"],
    },
    {
        "disease": "Osteoporosis",
        "symptoms": ["often silent", "back pain", "height loss", "fragility fractures"],
        "possible_causes": ["low bone mineral density"],
        "risk_factors": ["postmenopausal status", "low calcium/vitamin D"],
        "recommended_tests": ["DEXA scan", "vitamin D", "calcium"],
        "specialist": "Orthopedic Specialist / Endocrinologist",
        "urgent_red_flags": ["hip fracture", "sudden severe back pain"],
        "basic_care": ["weight-bearing exercise", "calcium and vitamin D guidance"],
    },
    {
        "disease": "Eczema (Atopic Dermatitis)",
        "symptoms": ["itchy skin", "dry patches", "redness", "skin cracking"],
        "possible_causes": ["skin barrier dysfunction", "allergic tendency"],
        "risk_factors": ["family atopy", "irritant exposure"],
        "recommended_tests": ["clinical diagnosis"],
        "specialist": "Dermatologist",
        "urgent_red_flags": ["widespread infection", "fever with skin lesions"],
        "basic_care": ["regular moisturization", "trigger avoidance"],
    },
    {
        "disease": "Psoriasis",
        "symptoms": ["thick scaly plaques", "itching", "dry cracked skin", "nail changes"],
        "possible_causes": ["immune-mediated skin inflammation"],
        "risk_factors": ["family history", "stress", "smoking"],
        "recommended_tests": ["clinical exam", "skin biopsy if uncertain"],
        "specialist": "Dermatologist",
        "urgent_red_flags": ["joint swelling", "widespread painful redness"],
        "basic_care": ["skin hydration", "dermatology follow-up"],
    },
    {
        "disease": "Acne Vulgaris",
        "symptoms": ["pimples", "blackheads", "whiteheads", "oily skin"],
        "possible_causes": ["hormonal influence", "follicular blockage"],
        "risk_factors": ["adolescence", "family history"],
        "recommended_tests": ["clinical exam"],
        "specialist": "Dermatologist",
        "urgent_red_flags": ["severe nodulocystic acne", "scarring"],
        "basic_care": ["gentle cleansing", "non-comedogenic products"],
    },
    {
        "disease": "Fungal Skin Infection",
        "symptoms": ["itchy ring-like rash", "skin peeling", "red borders", "scaling"],
        "possible_causes": ["dermatophyte infection"],
        "risk_factors": ["humidity", "sweating", "shared towels"],
        "recommended_tests": ["KOH mount", "clinical exam"],
        "specialist": "Dermatologist",
        "urgent_red_flags": ["rapid spread", "secondary bacterial infection"],
        "basic_care": ["keep skin dry", "antifungal treatment guidance"],
    },
    {
        "disease": "Depression",
        "symptoms": ["persistent low mood", "loss of interest", "sleep changes", "fatigue"],
        "possible_causes": ["multifactorial psychosocial and biological factors"],
        "risk_factors": ["chronic stress", "family history", "chronic illness"],
        "recommended_tests": ["clinical psychiatric evaluation"],
        "specialist": "Psychiatrist / Clinical Psychologist",
        "urgent_red_flags": ["self-harm thoughts", "suicidal ideation"],
        "basic_care": ["seek mental health support", "sleep routine", "social support"],
    },
    {
        "disease": "Generalized Anxiety Disorder",
        "symptoms": ["excessive worry", "restlessness", "muscle tension", "poor concentration"],
        "possible_causes": ["neurochemical and psychosocial factors"],
        "risk_factors": ["stressful life events", "family history"],
        "recommended_tests": ["clinical mental health assessment"],
        "specialist": "Psychiatrist / Clinical Psychologist",
        "urgent_red_flags": ["panic with chest pain", "self-harm thoughts"],
        "basic_care": ["breathing exercises", "therapy", "sleep hygiene"],
    },
    {
        "disease": "Insomnia",
        "symptoms": ["difficulty falling asleep", "frequent waking", "non-restorative sleep", "daytime tiredness"],
        "possible_causes": ["stress", "poor sleep habits", "medical conditions"],
        "risk_factors": ["irregular schedule", "excess caffeine"],
        "recommended_tests": ["sleep history", "sleep study if indicated"],
        "specialist": "Psychiatrist / Sleep Specialist",
        "urgent_red_flags": ["severe daytime impairment", "depression symptoms"],
        "basic_care": ["fixed sleep schedule", "screen reduction before bed"],
    },
    {
        "disease": "Obesity",
        "symptoms": ["high BMI", "fatigue", "joint pain", "snoring"],
        "possible_causes": ["calorie imbalance", "metabolic factors"],
        "risk_factors": ["sedentary lifestyle", "high-calorie diet"],
        "recommended_tests": ["BMI/waist assessment", "metabolic panel", "HbA1c"],
        "specialist": "Endocrinologist / Nutrition Specialist",
        "urgent_red_flags": ["breathing pauses during sleep", "chest pain with exertion"],
        "basic_care": ["structured diet plan", "physical activity", "behavior change"],
    },
    {
        "disease": "Vitamin D Deficiency",
        "symptoms": ["bone pain", "muscle weakness", "fatigue", "frequent infections"],
        "possible_causes": ["low sunlight exposure", "poor intake"],
        "risk_factors": ["indoor lifestyle", "darker skin", "malabsorption"],
        "recommended_tests": ["serum 25-hydroxy vitamin D", "calcium"],
        "specialist": "General Physician",
        "urgent_red_flags": ["severe muscle weakness", "recurrent fractures"],
        "basic_care": ["sun exposure", "dietary improvement", "supplements as advised"],
    },
    {
        "disease": "Dengue Fever",
        "symptoms": ["high fever", "severe body ache", "headache", "rash"],
        "possible_causes": ["dengue virus via Aedes mosquito"],
        "risk_factors": ["mosquito exposure in endemic areas"],
        "recommended_tests": ["NS1 antigen", "IgM", "CBC platelet count"],
        "specialist": "General Physician / Infectious Disease Specialist",
        "urgent_red_flags": ["bleeding", "persistent vomiting", "abdominal pain"],
        "basic_care": ["hydration", "strict medical monitoring"],
    },
    {
        "disease": "Malaria",
        "symptoms": ["cyclical fever", "chills", "sweating", "headache"],
        "possible_causes": ["Plasmodium infection via Anopheles mosquito"],
        "risk_factors": ["travel to endemic area", "no mosquito protection"],
        "recommended_tests": ["peripheral smear", "rapid malaria antigen test"],
        "specialist": "General Physician / Infectious Disease Specialist",
        "urgent_red_flags": ["confusion", "jaundice", "breathing distress"],
        "basic_care": ["prompt antimalarial treatment", "hydration"],
    },
    {
        "disease": "Typhoid Fever",
        "symptoms": ["prolonged fever", "abdominal pain", "weakness", "constipation or diarrhea"],
        "possible_causes": ["Salmonella typhi infection"],
        "risk_factors": ["unsafe water", "poor sanitation"],
        "recommended_tests": ["blood culture", "CBC", "Widal where appropriate"],
        "specialist": "General Physician",
        "urgent_red_flags": ["severe abdominal pain", "persistent vomiting", "altered sensorium"],
        "basic_care": ["safe fluids", "medical treatment adherence"],
    },
    {
        "disease": "Tuberculosis",
        "symptoms": ["chronic cough", "weight loss", "night sweats", "fever"],
        "possible_causes": ["Mycobacterium tuberculosis"],
        "risk_factors": ["close contact", "immunocompromised state", "malnutrition"],
        "recommended_tests": ["sputum GeneXpert", "chest X-ray", "culture"],
        "specialist": "Pulmonologist / Infectious Disease Specialist",
        "urgent_red_flags": ["coughing blood", "severe breathlessness"],
        "basic_care": ["strict medication adherence", "nutrition support", "infection control"],
    },
    {
        "disease": "Hepatitis A",
        "symptoms": ["jaundice", "fatigue", "nausea", "dark urine"],
        "possible_causes": ["hepatitis A virus"],
        "risk_factors": ["contaminated food/water", "poor sanitation"],
        "recommended_tests": ["LFT", "anti-HAV IgM"],
        "specialist": "Gastroenterologist / Hepatologist",
        "urgent_red_flags": ["persistent vomiting", "confusion", "bleeding tendency"],
        "basic_care": ["rest", "hydration", "liver-friendly diet"],
    },
    {
        "disease": "Hepatitis B",
        "symptoms": ["jaundice", "fatigue", "abdominal discomfort", "joint pain"],
        "possible_causes": ["hepatitis B virus"],
        "risk_factors": ["unsafe injections", "unprotected sex", "blood exposure"],
        "recommended_tests": ["HBsAg", "HBV DNA", "LFT"],
        "specialist": "Gastroenterologist / Hepatologist",
        "urgent_red_flags": ["confusion", "swelling abdomen", "bleeding"],
        "basic_care": ["avoid alcohol", "regular liver follow-up"],
    },
    {
        "disease": "Appendicitis",
        "symptoms": ["right lower abdominal pain", "nausea", "fever", "loss of appetite"],
        "possible_causes": ["appendix inflammation/obstruction"],
        "risk_factors": ["younger age"],
        "recommended_tests": ["clinical exam", "ultrasound", "CT abdomen"],
        "specialist": "General Surgeon",
        "urgent_red_flags": ["severe worsening pain", "rigid abdomen", "high fever"],
        "basic_care": ["urgent hospital evaluation", "avoid self-medication delay"],
    },
    {
        "disease": "Gallstones (Cholelithiasis)",
        "symptoms": ["right upper abdominal pain", "nausea", "vomiting", "pain after fatty meals"],
        "possible_causes": ["cholesterol/pigment stone formation"],
        "risk_factors": ["female sex", "obesity", "middle age"],
        "recommended_tests": ["abdominal ultrasound", "LFT"],
        "specialist": "General Surgeon / Gastroenterologist",
        "urgent_red_flags": ["fever with pain", "jaundice", "persistent vomiting"],
        "basic_care": ["low-fat diet", "timely surgical consult"],
    },
    {
        "disease": "Chronic Kidney Disease",
        "symptoms": ["fatigue", "leg swelling", "reduced appetite", "foamy urine"],
        "possible_causes": ["diabetes", "hypertension", "chronic nephritis"],
        "risk_factors": ["long-standing diabetes", "long-standing hypertension"],
        "recommended_tests": ["serum creatinine", "eGFR", "urine protein", "ultrasound"],
        "specialist": "Nephrologist",
        "urgent_red_flags": ["very low urine output", "severe breathlessness", "confusion"],
        "basic_care": ["BP and sugar control", "renal diet guidance", "regular nephrology follow-up"],
    },
    {
        "disease": "Epilepsy",
        "symptoms": ["recurrent seizures", "staring spells", "loss of awareness", "post-episode confusion"],
        "possible_causes": ["abnormal brain electrical activity"],
        "risk_factors": ["head injury", "stroke", "family history"],
        "recommended_tests": ["EEG", "brain MRI"],
        "specialist": "Neurologist",
        "urgent_red_flags": ["seizure > 5 minutes", "repeated seizures without recovery"],
        "basic_care": ["medication adherence", "sleep regularity", "avoid known triggers"],
    },
]


def get_disease_by_name(name: str) -> Dict[str, object] | None:  # Find one disease record by its name.
    normalized_name = name.strip().lower()  # Normalize input for case-insensitive matching.
    for disease in COMMON_DISEASES:  # Loop through all disease records.
        if str(disease["disease"]).lower() == normalized_name:  # Compare normalized names.
            return disease  # Return the first exact match.
    return None  # Return None if no record is found.


def list_disease_names() -> List[str]:  # Return all disease names in order.
    return [str(disease["disease"]) for disease in COMMON_DISEASES]  # Build and return name list.


def print_usage_note() -> None:  # Print a medical safety note for users.
    print("This dataset is for educational use only and not a medical diagnosis tool.")  # Safety disclaimer.
    print("Always consult a qualified doctor for diagnosis and treatment.")  # Safety disclaimer.


if __name__ == "__main__":  # Run demo output only when this file is executed directly.
    print_usage_note()  # Print safety notes first.
    print(f"Total diseases: {len(COMMON_DISEASES)}")  # Show count to confirm 50 entries.
    print("First 10 disease names:")  # Print a title for quick preview.
    for disease_name in list_disease_names()[:10]:  # Iterate over first 10 diseases.
        print(f"- {disease_name}")  # Print each disease name as a bullet.
